import fs from 'node:fs';
import path from 'node:path';
import { segmentSortKey, tripDays } from './model.js';
import { settleTrip } from './settle.js';
import { tripCoverage } from './coverage.js';

// One-way markdown mirror of the JSON data: one note per trip, a loyalty
// summary, and an insurance summary — YAML frontmatter, wikilink-friendly
// filenames, readable in Obsidian and by AI agents. Regenerable at any time;
// never hand-edited (every note carries MARKER, and only marked notes are
// ever cleaned up, so pointing MIRROR_DIR at an existing folder is safe).

export const MARKER = '<!-- generated by tripfolio — edits here are overwritten; edit in the app -->';

const noteName = (name) => String(name).replace(/[\\/:*?"<>|#^[\]]+/g, '').trim() || 'Untitled';
const today = () => new Date().toISOString().slice(0, 10);

function fm(fields) {
  const lines = ['---'];
  for (const [k, v] of Object.entries(fields)) {
    if (v === undefined || v === null || (Array.isArray(v) && !v.length)) continue;
    lines.push(Array.isArray(v) ? `${k}: [${v.join(', ')}]` : `${k}: ${v}`);
  }
  lines.push('---');
  return lines.join('\n');
}

function table(headers, rows) {
  if (!rows.length) return '*None yet.*';
  return [
    `| ${headers.join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((r) => `| ${r.map((c) => (c ?? '—')).join(' | ')} |`)
  ].join('\n');
}

const segmentLine = {
  flight: (s) => `**${s.airline || ''} ${s.flightNo || ''}** ${s.from || '?'} → ${s.to || '?'}, dep ${s.depLocal || '?'}${s.arrLocal ? `, arr ${s.arrLocal}` : ''}${s.cabin ? ` · ${s.cabin}` : ''}${s.seat ? ` · seat ${s.seat}` : ''}${s.pnr ? ` · PNR \`${s.pnr}\`` : ''}`,
  stay: (s) => `**${s.property || 'Stay'}** ${s.checkIn || '?'} → ${s.checkOut || '?'}${s.confirmationNo ? ` · conf \`${s.confirmationNo}\`` : ''}`,
  transport: (s) => `**${s.mode || 'Transport'}${s.operator ? ` (${s.operator})` : ''}** ${s.from || '?'} → ${s.to || '?'}${s.depLocal ? `, dep ${s.depLocal}` : ''}${s.ref ? ` · ref \`${s.ref}\`` : ''}`,
  activity: (s) => `**${s.name || 'Activity'}**${s.date ? ` ${s.date}` : ''}${s.location ? ` · ${s.location}` : ''}${s.ref ? ` · ref \`${s.ref}\`` : ''}`
};

function tripNote(trip, data) {
  const travelers = (trip.travelerIds || [])
    .map((id) => data.travelers.find((t) => t.id === id)?.name)
    .filter(Boolean);
  const segments = data.segments
    .filter((s) => s.tripId === trip.id)
    .sort((a, b) => segmentSortKey(a).localeCompare(segmentSortKey(b)));
  const candidates = data.candidates.filter((c) => c.tripId === trip.id && c.verdict !== 'promoted');

  const coverage = tripCoverage(trip, data.policies || [], data.travelers);
  const best = coverage.policies?.find((p) => p.policyId === coverage.best);
  const coverageLine = coverage.status === 'unknown' ? null :
    `Insurance: **${coverage.status}**${best ? ` — ${best.label}` : ''}` +
    (best?.uncoveredTravelers?.length ? ` · NOT covered: ${best.uncoveredTravelers.join(', ')}` : '');

  const parts = [
    fm({
      type: 'trip', status: trip.status, start: trip.startDate, end: trip.endDate,
      destinations: trip.destinations, travelers,
      insurance: coverage.status !== 'unknown' ? coverage.status : undefined,
      updated: today(), tags: ['tripfolio', 'trip']
    }),
    MARKER,
    `# ${trip.name}`,
    ...(coverageLine ? ['', coverageLine] : []),
    '',
    '## Bookings',
    segments.length
      ? segments.map((s) => `- ${(segmentLine[s.type] || segmentLine.activity)(s)}${s.notes ? ` — ${s.notes}` : ''}`).join('\n')
      : '*None yet.*'
  ];

  if (candidates.length) {
    parts.push('', '## Candidates (not booked)', table(
      ['Type', 'What', 'Price', 'Verdict'],
      candidates.map((c) => [
        c.type,
        (segmentLine[c.type] || segmentLine.activity)(c).replaceAll('|', '\\|'),
        c.price != null ? `${c.price} ${c.currency || ''}` : null,
        c.verdict
      ])
    ));
  }

  const settlement = settleTrip(trip, data.expenses || [], {
    cards: data.cards || [], exchanges: data.exchanges || [], travelers: data.travelers
  });
  if (settlement.rows.length) {
    parts.push('', '## Expenses',
      `Total spend: **S$${settlement.totalSpend.toFixed(2)}**` +
      (settlement.pendingCount ? ` (+${settlement.pendingCount} pending a rate)` : '') +
      (settlement.estimatedCount ? ` · ${settlement.estimatedCount} on estimated rates` : ''), '',
      table(['Person', 'Paid', 'Share', 'Net'],
        settlement.balances.map((b) => [b.name, `S$${b.paid.toFixed(2)}`, `S$${b.share.toFixed(2)}`, `S$${b.net.toFixed(2)}`])));
    if (settlement.transfers.length) {
      parts.push('', ...settlement.transfers.map((t) => `- ${t.fromName} pays ${t.toName} **S$${t.amount.toFixed(2)}**`));
    }
  }

  const days = tripDays(trip);
  const itinerary = trip.days || [];
  if (days.length || itinerary.length) {
    parts.push('', '## Itinerary');
    const dates = days.length ? days : itinerary.map((d) => d.date);
    for (const date of dates) {
      const entry = itinerary.find((d) => d.date === date);
      parts.push('', `### ${date}`, '', entry?.md?.trim() || '*Unplanned.*');
    }
  }

  return { file: `${noteName(trip.name)}.md`, content: parts.join('\n') + '\n' };
}

function loyaltyNote(data) {
  const rows = (kind) => data.programs
    .filter((p) => p.kind === kind)
    .map((p) => {
      const latest = (p.snapshots || []).slice().sort((a, b) => a.date.localeCompare(b.date)).at(-1);
      return [p.program, p.alliance, `\`${p.memberNumber}\``, p.tier, p.tierExpiry,
        latest ? `${latest.points.toLocaleString('en-SG')} (as of ${latest.date})` : null];
    });
  const headers = ['Program', 'Alliance', 'Member no.', 'Tier', 'Tier expiry', 'Points'];
  return {
    file: 'Loyalty Wallet.md',
    content: [
      fm({ type: 'loyalty-wallet', updated: today(), tags: ['tripfolio', 'loyalty'] }),
      MARKER,
      '# Loyalty Wallet', '',
      '## Airlines', rows('airline').length ? table(headers, rows('airline')) : '*None yet.*', '',
      '## Hotels', rows('hotel').length ? table(headers, rows('hotel')) : '*None yet.*'
    ].join('\n') + '\n'
  };
}

function insuranceNote(data) {
  const upcoming = data.trips.filter((t) => t.status !== 'done' && t.startDate);
  const coverageRows = upcoming.map((t) => {
    const c = tripCoverage(t, data.policies || [], data.travelers);
    const best = c.policies.find((p) => p.policyId === c.best);
    return [`[[${noteName(t.name)}]]`, `${t.startDate} → ${t.endDate}`, c.status,
      best ? best.label + (best.uncoveredTravelers.length ? ` · NOT covered: ${best.uncoveredTravelers.join(', ')}` : '') : null];
  });
  return {
    file: 'Travel Insurance.md',
    content: [
      fm({ type: 'travel-insurance', updated: today(), tags: ['tripfolio', 'insurance'] }),
      MARKER,
      '# Travel Insurance', '',
      '## Policies',
      table(
        ['Insurer', 'Policy no.', 'Type', 'Coverage', 'Max trip days', 'Regions', 'PDF'],
        data.policies.map((p) => [
          p.insurer, `\`${p.policyNumber}\``, p.type,
          p.coverageStart && p.coverageEnd ? `${p.coverageStart} → ${p.coverageEnd}` : null,
          p.maxTripDays, Array.isArray(p.regions) ? p.regions.join(', ') : p.regions,
          p.pdfPath ? 'on file' : 'not on file'
        ])
      ),
      '',
      '## What each policy covers',
      data.policies.length
        ? data.policies.map((p) => {
          const sgd = (n) => `S$${Number(n).toLocaleString('en-SG')}`;
          const rows = p.benefits?.length
            ? p.benefits.map((b) => [b.name, b.limit != null ? sgd(b.limit) : 'covered'])
            : [['Overseas medical', p.limits?.medical], ['Trip cancellation', p.limits?.cancellation], ['Baggage', p.limits?.baggage]]
              .filter((r) => r[1] != null).map((r) => [r[0], sgd(r[1])]);
          return [
            `### ${p.insurer} ${p.policyNumber}`,
            p.notes ? `*${p.notes}*\n` : null,
            rows.length ? table(['Benefit', 'Sum insured'], rows)
              : '*No benefit amounts on file — the sums insured are set by the plan; read the policy wording (or ingest it with an AI agent).*'
          ].filter((x) => x != null).join('\n');
        }).join('\n\n')
        : '*No policies on file.*',
      '',
      '## Coverage by trip',
      coverageRows.length ? table(['Trip', 'Dates', 'Status', 'Policy'], coverageRows) : '*No upcoming trips.*',
      '',
      '*Dates, trip length and travelers checked strictly; regions and fine print need the policy document.*'
    ].join('\n') + '\n'
  };
}

function indexNote(data, tripFiles) {
  const byStatus = (status) => data.trips
    .filter((t) => t.status === status)
    .map((t) => `- [[${noteName(t.name)}]]${t.startDate ? ` — ${t.startDate}${t.endDate ? ` → ${t.endDate}` : ''}` : ''}`);
  const section = (title, lines) => (lines.length ? [`## ${title}`, ...lines, ''] : []);
  return {
    file: 'Tripfolio.md',
    content: [
      fm({ type: 'tripfolio-index', updated: today(), tags: ['tripfolio'] }),
      MARKER,
      '# Tripfolio', '',
      ...section('Booked', byStatus('booked')),
      ...section('Planning', byStatus('planning')),
      ...section('Dreaming', byStatus('dreaming')),
      ...section('Done', byStatus('done')),
      '## Reference', '- [[Loyalty Wallet]]', '- [[Travel Insurance]]'
    ].join('\n') + '\n'
  };
}

export function collectMirrorData(store, seeds) {
  const data = {};
  for (const name of ['trips', 'segments', 'candidates', 'travelers', 'programs', 'policies', 'expenses', 'exchanges', 'cards']) {
    data[name] = store.read(name, seeds[name]);
  }
  return data;
}

// Remove previously generated notes (ours carry MARKER) that no longer have a
// counterpart — e.g. a renamed or deleted trip. Never touches unmarked files.
function cleanStale(dir, keep) {
  for (const entry of fs.readdirSync(dir)) {
    if (!entry.endsWith('.md') || keep.has(entry)) continue;
    const file = path.join(dir, entry);
    if (fs.readFileSync(file, 'utf8').includes(MARKER)) fs.unlinkSync(file);
  }
}

export function generateMirror(data, mirrorDir) {
  const tripsDir = path.join(mirrorDir, 'trips');
  fs.mkdirSync(tripsDir, { recursive: true });

  const tripNotes = data.trips.map((t) => tripNote(t, data));
  const rootNotes = [loyaltyNote(data), insuranceNote(data), indexNote(data, tripNotes)];

  for (const { file, content } of tripNotes) fs.writeFileSync(path.join(tripsDir, file), content, 'utf8');
  for (const { file, content } of rootNotes) fs.writeFileSync(path.join(mirrorDir, file), content, 'utf8');
  cleanStale(tripsDir, new Set(tripNotes.map((n) => n.file)));
  cleanStale(mirrorDir, new Set(rootNotes.map((n) => n.file)));

  return { notes: tripNotes.length + rootNotes.length, dir: mirrorDir };
}
